### ISSUE TITLE
Repeating Fields Issue

### ISSUE THREAD

**Issue by Raistlfiren** [zomars/bolt-store-hours#1]
If users use this as a repeating field it will not work. (Although, I don't know why you would need to) You should not include JS in the field type as you have done. I would include it in an external script and carry the attributes or options through data attributes. The repeating field uses `text/templates` and will break any field types with `script` in them. I would recommend doing something similar to this - https://github.com/Raistlfiren/FAIconFieldType

I would also recommend removing https://github.com/zomars/bolt-store-hours/blob/master/src/StoreHoursExtension.php#L35 so it displays 

``` php
    /**
     * {@inheritdoc}
     */
    protected function registerTwigPaths()
    {
        return [
            'templates',
        ];
    }
```

**Comment by zomars** [comment]
Ok I started reworking on this I still to work on the JS a little more.
